services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=pdf'
      - 'POSTGRES_PASSWORD=pdf'
      - 'POSTGRES_USER=pdf'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
